export default [
  'House Fire',
  'Vehicle Fire',
  'Heroin Found',
  'Needle',
  'Meth Found',
  'Crack Found',
  'Crazy Homeless Person',
  'Marijuana Found',
  'Cocaine Found',
  'Someone says "I didn\'t do anything"',
  'Car Chase',
  'Search Warrant',
  'House Break-in',
  'Excessive Speeding',
  'DUI',
  'K-9 Pursuing Suspects',
  'Shooting',
  'Naked Person',
  'Fight',
  'Girl Fight',
  'Domestic Violence',
  'Public Intoxication',
  'Noise Complaint',
  'Bloody Face',
  'Resisting Arrest',
  'Gun in Car',
  'Assaulting an Officer',
  'Responding to a Robbery',
  'Underage Drinking',
  'Road Rage',
  'License Suspended / Revoked',
  'Domestic Dispute',
  'Suspicious Vehicle',
  'Guns Drawn',
  'Child Endangerment',
  'They\'re recording me, not you',
  'Smell of Marijuana',
  'Threaten to Sue',
  'Animal Abuse',
  'Overdose',
  'Outstanding Warrant',
  'Running from Cops',
  'Obstructing Justice',
  'Burglary',
  'Suspect in Custody',
  'Breathalyzer',
  'Car Accident',
  'Miranda Rights Read',
  'Person Tased',
  'Open Container',
  'Foot Pursuit',
  'No Insurance',
  'Drug Paraphernalia',
  'Helicopter in Use',
  'Pills',
  'Stolen Car',
  'Child Neglect',
  'Trespassing',
  'Stabbing',
  'Intent To Distribute'


];

